config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  get 'articles/:article_id/comments', to: 'articles#index'
  resources :articles do
  	resources :comments, only: [:index, :create, :new]
  end
  resources :comments, only: [:update, :edit, :show, :destroy]
  #get 'welcome', to: 'welcome#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

	include ActiveModel::SecurePassword

	has_many :comments, dependent: :destroy
	validates :title, presence: true
	#validates :title, uniqueness: {case_sensitive: false} 
	validates :title, on: [:create, :update], format: {with: /\A[a-zA-Z ?]+\z/ , message: "only allows letters"}  



end

app/models/comment.rb
class Comment < ApplicationRecord
 	belongs_to :article
  	validates :commenter, presence: true
  	validates :commenter, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	
	helper ArticlesHelper

	http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
	before_action :params_find, only: [:show, :edit, :update, :destroy]
	def index
		@articles = Article.all
		@articles = @articles.sort_by {|article| article.created_at }
	end

	def new
		 @article = Article.new
	end

	def create
		@article = Article.new(params_article)

		if @article.save
			flash[:notice] = "Successfully created product."
			redirect_to @article
		else
			render new_article_path
		end

	end

	def edit
	end

	def update
		if @article.update(params_article)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		@article.destroy

		redirect_to articles_path
	end
	def show
	end

	private
	def params_find
		@article = Article.find(params[:id])
	end

	def params_article
		params.require(:article).permit(:title, :text)
	end
 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

	def new
		@comment = Comment.new
	end
	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(params_comment)
		if(@comment.save)
			redirect_to article_path(@article)
		else
			render 'comments/error'
		end
	end

	def destroy
		comment = Comment.find(params[:id])
		article = comment.article
		comment.destroy
		redirect_to article_path(article.id)
	end

	private
	def params_comment
		params.require(:comment).permit(:commenter, :body)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/articles_helper.rb
module ArticlesHelper
	def hello_blog
    	"This is my bLog"
 	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
	<% if @article.errors.any? %>
	<div id="error_explanation">
		<h2>
			<%= pluralize(@article.errors.count, "error") %> prohibited this  article from being saved:
		</h2>
		<ul>
			<%= @article.errors.full_messages.each do |msg| %>
			<li> <%= msg %> </li>
			<%end %>
		</ul>
	</div>
	<%end%>


	<p>
		<%= form.label :title %> <br>
		<%= form.text_field :title %>
	</p>

	<p>
		<%= form.label :text %> <br>
		<%= form.text_area :text %>
	</p>
	<p >
		<%= form.submit({:class => 'btn btn-primary' }) %>
	</p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>
<%= link_to 'Back', article_path(@article.id), :class => 'btn btn-default', style: "color: Peru" %>

app/views/articles/index.html.erb
<h1 style= "color: Peru"><%= hello_blog %><br></h1>
<%= link_to 'New Article', new_article_path, style: "color: yellow" %>
<table>
	<tr>
		<th style= "color: Peru">Title </th>
		<th style= "color: Peru">Text</th>
		<th></th>
	</tr>

	<%@articles.each do|article| %>
		<tr>
			<td style="padding-right: 10px"><%= article.title %></td>
			<td><%= article.text %></td>
			<td style="padding-left: 10px"><%= link_to 'show',article_path(article), style: "color: green;" %></td>
		</tr>
	<%end%>
</table>

app/views/articles/new.html.erb
<h1>New Article</h1>


<%= render 'form' %>
<%= image_tag "image.jpg" %><br>
<%= link_to 'Back', articles_path , :class => 'btn btn-default', style: "color: Peru" %>

app/views/articles/show.html.erb
<p>
	<strong style= "color: Peru">Title:</strong>
	 <%= @article.title %>
</p>

<p>
	<strong style= "color: Peru">Text:</strong>
	<%= @article.text %>
</p>
<p></p>

<h2>Comments</h2>
<%= render @article.comments %>
	




<h2>Add a new comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Back',  articles_path, :class => 'btn btn-default', style: "color: Peru" %>

<%= link_to 'Edit', edit_article_path, :class => 'btn btn-default', style: "color: Lime" %>


<%= link_to 'Destroy', article_path(@article), :class => 'btn btn-default',style: "color: red", method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/comments/_comment.html.erb
	<p>
		<strong style= "color: Peru"><%= comment.id %></strong><br>
		<strong style= "color: Peru">Commenter:</strong>
		<%= comment.commenter %>
	</p>
	<p>
		<strong style= "color: Peru">Comment:</strong>
		<%= comment.body %>
	</p>
	
	<%= link_to 'Destory Comment', [comment], :class => 'btn btn-default',style: "color: red", method: :delete, data: {confirm: "Are you sure?"} %>

app/views/comments/_form.html.erb
<%= form_with(model: [@article, @article.comments.build],local: true) do |form| %>
<p>
	<%= form.label :commenter %><br>
	<%= form.text_field :commenter  %>
</p>
<p>
	<%= form.label :body %><br>
	<%= form.text_field :body %>
</p>
<p>
	<%= form.submit  %>
</p>
<%end%>

app/views/comments/error.html.erb
<%= form_with(model: @comment_path,local: true) do |form| %>
	
	<% if @comment.errors.any? %>
		<div id="error_explanation">
			<h2>
				
				<%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:
			</h2>
			<ul>
				<%= @comment.errors.full_messages.each do |msg| %>
				<li> <%= msg %> </li>
				<%end %>
			</ul>
		</div>
	<%end%>

		<% @article = @comment.article %>
		
	<%= link_to "Back", article_path(@article.id)%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

   
    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
    <%= javascript_include_tag 'application', media: 'all', 'data-turbolinks-track' => false %>
  </head>

  <body>
    


  <nav class="navbar navbar-default">
    <a class="navbar-brand" href="#">My blog </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar navbar-collapse" > 
      <ul class="nav navbar-nav" style ="display: inline-block"  #important>
        <li><%= link_to 'Home', root_path, style: "display: inline-block"%></li>
        <li><%= link_to 'New Article', new_article_path, style: "display: inline-block"%></li> 
      </ul>
    </div>
  </nav>

<!--  <%= link_to 'Home', root_path, style: "color: yellow;"%>
  <%= link_to 'New Post', new_article_path, style: "color: yellow" %> -->
   



    <div class="container">
    </div>
    
   
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>hello Ruby</h1>
<%= link_to 'My Blog', articles_path%>